server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 如果需要代理 .NET API
    location /api/ {
        proxy_pass http://host.docker.internal:8080/; # 或者写成后端容器名字
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}